sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aruntv1986/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aruntv1986/docker-react npm run test
